### ISSUE TITLE
Add support for specifying Basepath

### ISSUE THREAD

**Issue by midwan** [Mouaijin/SubsonicSharp#1]
In the ServerInfo, you can currently only specify Address and Port.
It would be useful to add support for a BasePath as well, since that is common in some installations.

For example, the following installation cannot be currently configured:
http://myserver.org:4040/somefolder

**Comment by Mouaijin** [comment]
Sure thing, I didn't really expect anyone else out there to try to use this so it's basically only set up to handle the needs I had at the time. I'll take a look into that as time permits.
