### ISSUE TITLE
Add support for HTTPS Urls

### ISSUE THREAD

**Issue by midwan** [Mouaijin/SubsonicSharp#2]
I noticed it's currently hardcoded to use HTTP URLs.
It would be good to add support for HTTPS as well, as an optional property of ServerInfo.

The final BaseUrl should look something like this:
{protocol}{host}{port}{basepath}

**Comment by Mouaijin** [comment]
I would welcome a pull request on this. I've been unable to configure Subsonic to run on HTTPS reliably using my current configuration (Arch Linux on an Intel NUC, Integrated Celeron chip). Since I have no way of testing it, I would have no idea whether it was working or not!
